[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/AstroNvim/template"
  refreshPeriod = "24h"
[".tmux"]
  type = "git-repo"
  url = "https://github.com/gpakosz/.tmux"
  refreshPeriod = "24h"
